// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase Web app.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else {
      throw UnsupportedError(
        'DefaultFirebaseOptions are only configured for the Web platform. '
        'Please run this app in a web environment.',
      );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJvFAGPKI2uhPPlZgJ2T14LAezeHFskt4',
    appId: '1:944914125311:web:3c4c1f3085797a461457ca',
    messagingSenderId: '944914125311',
    projectId: 'west-valley-gardens-6682-c1018',
    authDomain: 'west-valley-gardens-6682-c1018.firebaseapp.com',
    databaseURL:
        'https://west-valley-gardens-6682-c1018-default-rtdb.firebaseio.com',
    storageBucket: 'west-valley-gardens-6682-c1018.appspot.com',
    measurementId: 'G-T34LPL88S9',
  );
}
